"""Fix Donations

Revision ID: e96df9a2077d
Revises: d4571d58f65b
Create Date: 2023-12-10 19:26:16.806532

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "e96df9a2077d"
down_revision = "d4571d58f65b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("donation", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("full_amount", sa.Integer(), nullable=True)
        )
        batch_op.add_column(
            sa.Column("invested_amount", sa.Integer(), nullable=True)
        )
        batch_op.add_column(
            sa.Column("fully_invested", sa.Boolean(), nullable=True)
        )
        batch_op.add_column(
            sa.Column("create_date", sa.DateTime(), nullable=True)
        )
        batch_op.add_column(
            sa.Column("close_date", sa.DateTime(), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("donation", schema=None) as batch_op:
        batch_op.drop_column("close_date")
        batch_op.drop_column("create_date")
        batch_op.drop_column("fully_invested")
        batch_op.drop_column("invested_amount")
        batch_op.drop_column("full_amount")

    # ### end Alembic commands ###
